name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Run a multi-line script
        run: pyinstaller -F launcher.py
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher
          path: dist/launcher
